(() => {
  $('.owl-carousel').owlCarousel({
    loop:true,
    responsiveClass:true,
    responsive:{
      0:{
        items:2,
        nav:true
      },
      600:{
        items:2,
        nav:false,
        loop:false
      },
      1000:{
        items:1,
        nav:true,
        loop:false
      }
    }
  })
})()